defaults: &defaults
  adapter: postgresql
  encoding: unicode

development_defaults: &development_defaults
  <<: *defaults
  user: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: localhost

development:
  <<: *development_defaults
  database: caffeine_dummy_dev

test:
  <<: *development_defaults
  database: caffeine_dummy_test
