# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 991dc79e90d2269d73a870312b47c7909410e226793bfd0d9810f3f9e1fa7dfb90f1b93897973d6890fbe4538dae5e8ed6bd5d7c8a2e867d31c4b59303b94744

test:
  secret_key_base: 4b8aec3b6949bab8ce813ff99fd453a75517cd522a136d50bf02074077a9c5643332ec959b302b1a504961f49b78e3632ad6fb011230767731bceec9a10e0316

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
